-- tuning-in/lib/scene_data.lua
-- the six scene parameter tables. the blend control interpolates between
-- adjacent scenes. every field is a plain number so the tables can be
-- lerped in-place (see lerp_scene_into in tuning-in.lua).

local scenes = {
  { -- 1: birdsong (blend 0.0) -- dawn, sparse bright dots drifting
    count = 10,
    dx = 0.4, dx_var = 0.3,
    dy = 0.0, dy_var = 0.1,
    brightness = 12, br_var = 3,
    trail = 0,
    spawn_y_min = 4, spawn_y_max = 44,
    spawn_x_min = 0, spawn_x_max = 128,
    horizon_y = 48, horizon_br = 6,
    bg_glow_y = 48, bg_glow_h = 16, bg_glow_br = 1,
    fade_above = -1,
    flicker = 0,
    sine_dy = 0,
  },
  { -- 2: forest (blend 1.0) -- dense, still, dappled brightness variance
    count = 35,
    dx = 0.0, dx_var = 0.04,
    dy = 0.0, dy_var = 0.02,
    brightness = 7, br_var = 4,
    trail = 0,
    spawn_y_min = 8, spawn_y_max = 56,
    spawn_x_min = 0, spawn_x_max = 128,
    horizon_y = 50, horizon_br = 4,
    bg_glow_y = -1, bg_glow_h = 0, bg_glow_br = 0,
    fade_above = -1,
    flicker = 0,
    sine_dy = 0,
  },
  { -- 3: rain (blend 2.0) -- dense diagonal streaks (calmed per addendum)
    count = 45,
    dx = -0.4, dx_var = 0.2,
    dy = 1.2, dy_var = 0.4,
    brightness = 5, br_var = 3,
    trail = 2.5,
    spawn_y_min = -4, spawn_y_max = 0,
    spawn_x_min = 0, spawn_x_max = 128,
    horizon_y = 54, horizon_br = 2,
    bg_glow_y = -1, bg_glow_h = 0, bg_glow_br = 0,
    fade_above = -1,
    flicker = 0,
    sine_dy = 0,
  },
  { -- 4: stream (blend 3.0) -- horizontal flow with sinusoidal shimmer
    count = 22,
    dx = 0.7, dx_var = 0.4,
    dy = 0.0, dy_var = 0.15,
    brightness = 9, br_var = 4,
    trail = 2,
    spawn_y_min = 24, spawn_y_max = 44,
    spawn_x_min = -4, spawn_x_max = 0,
    horizon_y = -1, horizon_br = 0,
    bg_glow_y = 28, bg_glow_h = 12, bg_glow_br = 1,
    fade_above = -1,
    flicker = 0,
    sine_dy = 0.3,
  },
  { -- 5: fire (blend 4.0) -- rising, flickering embers over a warm glow
    count = 30,
    dx = 0.0, dx_var = 0.2,
    dy = -1.2, dy_var = 0.5,
    brightness = 10, br_var = 5,
    trail = 0,
    spawn_y_min = 56, spawn_y_max = 64,
    spawn_x_min = 20, spawn_x_max = 108,
    horizon_y = -1, horizon_br = 0,
    bg_glow_y = 48, bg_glow_h = 16, bg_glow_br = 2.5,
    fade_above = 20,
    flicker = 1,
    sine_dy = 0,
  },
  { -- 6: night (blend 5.0) -- near black, a few dim twinkling stars
    count = 6,
    dx = 0.0, dx_var = 0.01,
    dy = 0.0, dy_var = 0.006,
    brightness = 4, br_var = 2,
    trail = 0,
    spawn_y_min = 8, spawn_y_max = 56,
    spawn_x_min = 8, spawn_x_max = 120,
    horizon_y = -1, horizon_br = 0,
    bg_glow_y = -1, bg_glow_h = 0, bg_glow_br = 0,
    fade_above = -1,
    flicker = 0,
    sine_dy = 0,
  },
}

return scenes
